=== Hemanth-Reddy-lab/EnterpriseProgramming/07-01-2021_EP-Skilling_Task/(07-01-2021)EP-Skilling-Task.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student+)>
<!ELEMENT student (num,name,email,marks,class)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT marks (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ATTLIST student sid ID #REQUIRED>

=== Hemanth-Reddy-lab/EnterpriseProgramming/07-01-2021_EP-Skilling_Task/(07-01-2021)EP-Skilling-Task.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "(07-01-2021)EP-Skilling-Task.dtd"> 
<?xml-stylesheet type="text/xsl" href="(07-01-2021)EP-Skilling-Task.xsl"?>

<students >
	<student sid="a">
		<num>190030286</num>
		<name>Mohan Vamsi</name>
		<email>190030286@kluniversity.in</email>
		<marks>98</marks>
		<class>1A</class>
	</student>
	<student sid="b">
		<num>190030430</num>
		<name>Rakesh</name>
		<email>190030430@kluniversity.in</email>
		<marks>98</marks>
		<class>1B</class>
	</student>
	<student sid="c">
		<num>190031152</num>
		<name>Akhil</name>
		<email>190031152@kluniversity.in</email>
		<marks>98</marks>
		<class>2A</class>
	</student>
	<student sid="d">
		<num>190031153</num>
		<name>Satish</name>
		<email>190031153@kluniversity.in</email>
		<marks>98</marks>
		<class>2B</class>
	</student>
	<student sid="e">
		<num>190030429</num>
		<name>Shiva</name>
		<email>19003429@kluniversity.in</email>
		<marks>98</marks>
		<class>1A</class>
	</student>
</students>
